version: '3.8'
# docker-compose -f docker-compose-app-v1.0.yml up -d
services:
  # 部署前端项目
  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/xfg-studio/nginx:latest
    container_name: nginx
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
    privileged: true
  # 部署后端项目 - 小型支付商城
  s-pay-mall-app:
    image: bin/s-pay-mall-ddd-bin-app:3.0
    container_name: s-pay-mall-app
    restart: on-failure
    ports:
      - "9091:8080"
    environment:
      - TZ=PRC
      - SERVER_PORT=8080
      - APP_CONFIG_GROUP_BUY_MARKET_API_URL=${APP_CONFIG_GROUP_BUY_MARKET_API_URL:-http://127.0.0.1}
      - APP_CONFIG_GROUP_BUY_MARKET_NOTIFY_URL=${APP_CONFIG_GROUP_BUY_MARKET_NOTIFY_URL:-http://127.0.0.1/api/v1/alipay/group_buy_notify}
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-change-me}
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/s-pay-mall-ddd-market?serverTimezone=UTC&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_HIKARI_POOL_NAME=Retail_HikariCP
      - WEIXIN_CONFIG_ORIGINALID=${WEIXIN_CONFIG_ORIGINALID:-change-me}
      - WEIXIN_CONFIG_TOKEN=${WEIXIN_CONFIG_TOKEN:-change-me}
      - WEIXIN_CONFIG_APP_ID=${WEIXIN_CONFIG_APP_ID:-change-me}
      - WEIXIN_CONFIG_APP_SECRET=${WEIXIN_CONFIG_APP_SECRET:-change-me}
      - WEIXIN_CONFIG_TEMPLATE_ID=${WEIXIN_CONFIG_TEMPLATE_ID:-change-me}
      - ALIPAY_NOTIFY_URL=${ALIPAY_NOTIFY_URL:-http://example.com/api/v1/alipay/alipay_notify_url}
      - ALIPAY_RETURN_URL=${ALIPAY_RETURN_URL:-http://127.0.0.1}
    volumes:
      - ./log:/data/log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - my-network
  # 拼团，负载01
  # 原镜像，需要自己构建；fuzhengwei/group-buy-market-app:3.0
  # 代理镜像（小傅哥打包好的，可以直接使用）； registry.cn-hangzhou.aliyuncs.com/xfg-studio/group-buy-market-app:3.0
  group-buy-market-01:
    image: bin/group-buy-market-bin-app:3.0
    container_name: group-buy-market-bin-app-01
    restart: on-failure
    ports:
      - "8091:8091"
    environment:
      - TZ=PRC
      - SERVER_PORT=8091
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-change-me}
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/group_buy_market?serverTimezone=UTC&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_HIKARI_POOL_NAME=Retail_HikariCP
      - REDIS_SDK_CONFIG_HOST=redis
      - REDIS_SDK_CONFIG_PORT=6379
      - XFG_WRENCH_CONFIG_SYSTEM=group-buy-market
      - XFG_WRENCH_CONFIG_REGISTER_HOST=redis
      - XFG_WRENCH_CONFIG_REGISTER_PORT=6379
      - LOGSTASH_HOST=logstash
    volumes:
      - ./log:/data/log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - my-network
  # # 拼团，负载02
  group-buy-market-02:
    image: bin/group-buy-market-bin-app:3.0
    container_name: group-buy-market-bin-app-02
    restart: on-failure
    ports:
      - "8092:8091"
    environment:
      - TZ=PRC
      - SERVER_PORT=8091
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-change-me}
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/group_buy_market?serverTimezone=UTC&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_HIKARI_POOL_NAME=Retail_HikariCP
      - REDIS_SDK_CONFIG_HOST=redis
      - REDIS_SDK_CONFIG_PORT=6379
      - XFG_WRENCH_CONFIG_SYSTEM=group-buy-market
      - XFG_WRENCH_CONFIG_REGISTER_HOST=redis
      - XFG_WRENCH_CONFIG_REGISTER_PORT=6379
    volumes:
      - ./log:/data/log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
